spring:
  application:
    name: turbine
server:
  port: 8989
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url.defaultZone: http://localhost:1111/eureka/
turbine:
  app-config: RIBBON-CONSUMER
  cluster-name-expression: new String("default")
  combine-host-port: true
