spring:
  application:
    name: feign-consumer
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
feign:
  hystrix:
    enabled: true
  client:
    config:
      hello-service:
        logger-level: FULL
logging:
  level:
    top.aceofspades.web.HelloService: DEBUG
