spring:
  application:
    name: api-gateway
server:
  port: 5555
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: hello-service
    api-b:
      path: /api-b/**
      serviceId: feign-consumer
  ignored-services: feign-consumer
#  ignored-patterns: /**/hello/**


management:
  endpoints:
    web:
      exposure:
        include: '*'