spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://localhost:7001/
server:
  port: 5556
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: hello-service
    api-b:
      path: /api-b/**
      serviceId: feign-consumer
  ignored-services: feign-consumer
