spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/duanbt/spring-cloud-learn.git
          search-paths: config-repo
server:
  port: 7001